// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"time"
)

type Article struct {
	ID           string    `db:"id"`
	AuthorID     string    `db:"author_id"`
	JudulArticle string    `db:"judul_article"`
	IsiArticle   string    `db:"isi_article"`
	Author       string    `db:"author"`
	ImageUrl     string    `db:"image_url"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type History struct {
	ID             string    `db:"id"`
	Uid            string    `db:"uid"`
	TotalKolestrol string    `db:"total_kolestrol"`
	Tingkat        string    `db:"tingkat"`
	ImageUrl       string    `db:"image_url"`
	CreatedAt      time.Time `db:"created_at"`
	UpdatedAt      time.Time `db:"updated_at"`
}

type User struct {
	ID        string    `db:"id"`
	Name      string    `db:"name"`
	Email     string    `db:"email"`
	BirthDate string    `db:"birth_date"`
	Gender    string    `db:"gender"`
	ImageUrl  string    `db:"image_url"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
