// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"context"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	DeleteArticle(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetArticle(ctx context.Context, id string) (Article, error)
	GetUser(ctx context.Context, id string) (User, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (string, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (string, error)
}

var _ Querier = (*Queries)(nil)
