CREATE TABLE IF NOT EXISTS history (
    id VARCHAR(150) PRIMARY KEY,
    uid VARCHAR(150) REFERENCES users (id) UNIQUE NOT NULL,
    total_kolestrol VARCHAR(255) NOT NULL,
    tingkat VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);